name: Deploy FastAPI Application

on: 
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main
  workflow_dispatch:  

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Train model
      run: python scripts/train_model.py
      env:
        PYTHONPATH: ${{ github.workspace }}

    - name: Public IP
      id: ip
      uses: haythem/public-ip@v1.3

    - name: Print Public IP
      run: |
        echo "Public IPv4: ${{ steps.ip.outputs.ipv4 }}"
        echo "Public IPv6: ${{ steps.ip.outputs.ipv6 }}"

    - name: Deploy FastAPI application
      run: uvicorn scripts.main:app --host ${{ steps.ip.outputs.ipv4 }} --port ${{ secrets.PORT || '8000' }}
      env:
        PYTHONPATH: ${{ github.workspace }}
