name: Deploy FastAPI Application

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main
  workflow_dispatch:  

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Train model
      run: python scripts/train_model.py
      env:
        PYTHONPATH: ${{ github.workspace }}

    - name: Deploy FastAPI application
      run: uvicorn main:app --host 0.0.0.0 --port ${{ secrets.PORT || '8000' }}
      env:
        PYTHONPATH: ${{ github.workspace }}
